딥러닝 모델링 시 입력 데이터의 형태를 변환해줘야 하는 경우가 많으며
이에 활용되는 함수를 알아보자

In [3]:
import numpy as np

In [ ]:
# 이미지 데이터의 경우 대부분 4개의 차원을 가짐
# 텐서플로우는 (n, w, h, c) 형태로 모델링


In [4]:
arr1 = np.random.randint(0,255, (30,30,3))

In [5]:
arr1.shape

(30, 30, 3)

In [6]:
arr1

array([[[192,  85, 195],
        [123,  56, 226],
        [252, 110, 168],
        ...,
        [ 48,  61,  37],
        [200, 197,  84],
        [159, 106, 248]],

       [[ 49,  22, 203],
        [227,  24, 162],
        [ 71, 246,  63],
        ...,
        [127,  40, 141],
        [ 91, 122, 166],
        [177, 103,   3]],

       [[ 50,   9,  81],
        [ 26, 111,   8],
        [154, 125, 254],
        ...,
        [ 91, 209, 112],
        [228,  56, 225],
        [137,  95, 124]],

       ...,

       [[ 77, 234,  36],
        [ 94, 174,  52],
        [ 42, 237, 178],
        ...,
        [ 83, 129,  38],
        [211,  25,  11],
        [ 51, 217, 218]],

       [[200,  27, 161],
        [ 32, 136,  52],
        [182,  63, 218],
        ...,
        [ 54, 161,  79],
        [217, 124, 121],
        [227, 163, 120]],

       [[ 44,  29, 113],
        [108,  76, 153],
        [ 79,  56, 175],
        ...,
        [100, 193, 232],
        [180,  29,  80],
        [ 77,  67,  33]]

expand_dims: 차원을 추가할 수 있다

In [7]:
# 1차원 추가하기
arr2 = np.expand_dims(arr1,0)  # 몇 번째에 추가할지 지정 가능

In [10]:
?np.expand_dims

In [8]:
arr2.shape

(1, 30, 30, 3)

In [11]:
arr3 = np.expand_dims(arr1,3)  # 몇 번째에 추가할지 지정 가능
arr3.shape

(30, 30, 3, 1)

squeeze: 차원 삭제

In [12]:
# 차원 삭제하기
arr3.squeeze(3).shape

(30, 30, 3)

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

reshape: 형태 변경

In [13]:
arr4 = np.arange(100).reshape(20,5)

In [14]:
arr4.shape

(20, 5)

In [15]:
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

transpose: 순서 변경

In [16]:
arr3.shape

(30, 30, 3, 1)

In [17]:
arr5=arr3.transpose(3,0,1,2)

In [19]:
arr5.shape

(1, 30, 30, 3)